# 第一章  机器学习基础
有预测表明，在本书出版后不久，20%的互联网非视频流量都将由物理传感器产生。

### 关键术语
- 特征（属性）
- 训练集
- 目标变量

### 主要任务
- 监督学习：分类和回归
- 无监督学习：聚类和密度估计

### NumPy函数库基础
如下所示。

In [1]:
from numpy import *

In [2]:
# 随机生辰一个4*4的数组
random.rand(4, 4);

array([[ 0.35824755,  0.39131792,  0.80147386,  0.61826803],
       [ 0.91718149,  0.27315736,  0.80646433,  0.51059557],
       [ 0.19995822,  0.81452937,  0.86783193,  0.05751934],
       [ 0.60091134,  0.36028954,  0.7314043 ,  0.14959695]])

In [3]:
# mat()函数将数组转化为矩阵
randMat = mat(random.rand(4,4))

In [4]:
randMat

matrix([[ 0.4634963 ,  0.57172293,  0.01944711,  0.91835888],
        [ 0.45346226,  0.15804127,  0.91528865,  0.05601048],
        [ 0.99323281,  0.0377259 ,  0.72530548,  0.11634979],
        [ 0.39178273,  0.79452642,  0.10549249,  0.91406826]])

In [5]:
# 矩阵求逆
invRandMat = randMat.I

In [6]:
randMat*invRandMat

matrix([[  1.00000000e+00,  -2.22044605e-16,   1.11022302e-16,
          -3.33066907e-16],
        [  1.11022302e-16,   1.00000000e+00,  -6.93889390e-17,
           0.00000000e+00],
        [  0.00000000e+00,  -8.32667268e-17,   1.00000000e+00,
           1.11022302e-16],
        [  7.21644966e-16,   5.55111512e-17,   0.00000000e+00,
           1.00000000e+00]])

In [9]:
# 有微小的误差，误差值可计算
myEye = randMat*invRandMat

In [10]:
myEye - eye(4)

matrix([[  4.44089210e-16,  -2.22044605e-16,   1.11022302e-16,
          -3.33066907e-16],
        [  1.11022302e-16,   2.22044605e-16,  -6.93889390e-17,
           0.00000000e+00],
        [  0.00000000e+00,  -8.32667268e-17,   4.44089210e-16,
           1.11022302e-16],
        [  7.21644966e-16,   5.55111512e-17,   0.00000000e+00,
          -5.55111512e-16]])

In [14]:
myEye

matrix([[  1.00000000e+00,  -2.22044605e-16,   1.11022302e-16,
          -3.33066907e-16],
        [  1.11022302e-16,   1.00000000e+00,  -6.93889390e-17,
           0.00000000e+00],
        [  0.00000000e+00,  -8.32667268e-17,   1.00000000e+00,
           1.11022302e-16],
        [  7.21644966e-16,   5.55111512e-17,   0.00000000e+00,
           1.00000000e+00]])

### 算法的一般流程
1. 收集数据
2. 准备数据
3. 分析数据
4. 训练算法
5. 测试算法
6. 使用算法